config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'
  get '/trial' => 'pages#trial'
  get '/company' => 'pages#company', as: :company
  get '/contact' => 'pages#contact', as: :contact
  get '/rcf' => 'pages#rcf', as: :rcf
  get '/rcf/gallery' => 'pages#rcf_gallery', as: :rcf_gallery
  get '/rct' => 'pages#rct', as: :rct
  get '/rct/gallery' => 'pages#rct_gallery', as: :rct_gallery
  get '/rcp' => 'pages#rcp', as: :rcp
  get '/rcp/gallery' => 'pages#rcp_gallery', as: :rcp_gallery
  get '/rcd' => 'pages#rcd', as: :rcd
  get '/rcd/gallery' => 'pages#rcd_gallery', as: :rcd_gallery
  get '/jpgv' => 'pages#jpgv', as: :jpgv
  get '/jpgv/gallery' => 'pages#jpgv_gallery', as: :jpgv_gallery
  get '/jpgv/sinotruk-cimc' => 'pages#jpgv_sinotruk', as: :jpgv_sinotruk
  get '/google980400ed5256881f.html' => 'pages#google_verification'
  get '/sitemap_www.xml' => 'pages#sitemap_www'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def company
  end

  def contact
  end

  def rcf
  end

  def rcf_gallery
  end

  def rct
  end

  def rct_gallery
  end

  def rcp
  end

  def rcp_gallery
  end

  def rcd
  end

  def rcd_gallery
  end

  def jpgv
  end

  def jpgv_gallery
  end

  def jpgv_sinotruk
  end

  def google_verification
    respond_to do |format|
      format.html { render :text => "google-site-verification: google980400ed5256881f.html"}
    end
  end

  # def sitemap
  #   render :file=>Rails.root.join(*%w( sitemap.xml)), :content_type => 'application/xml', :layout => false
  # end

  def sitemap_www
    render :file=>Rails.root.join(*%w( sitemap_www.xml)), :content_type => 'application/xml', :layout => false
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= metamagic %>
  <% if current_page?(rcf_gallery_path) || current_page?(rct_gallery_path) || current_page?(rcd_gallery_path) || current_page?(rcp_gallery_path) || current_page?(jpgv_sinotruk_path) || current_page?(jpgv_gallery_path) %>
    <meta name="robots" content="noindex">
  <% end %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js">
  </script>
  <%= csrf_meta_tags %>
  <link href='https://fonts.googleapis.com/css?family=Lora:400,400italic,700,700italic' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Titillium+Web:400,300,700,600' rel='stylesheet' type='text/css'>
</head>
<body>

<%= yield %>
<%= javascript_include_tag 'scroll', 'data-turbolinks-track' => true %>
<%= javascript_include_tag 'navbar', 'data-turbolinks-track' => true %>
<%= javascript_include_tag 'customers', 'data-turbolinks-track' => true %>
</body>
</html>

app/views/pages/_navbar.html.erb
<div class="container-fluid">

  <div class="navbar-header">
    <a class="navbar-brand" href="/"><%=image_tag "https://s3.amazonaws.com/royalclass/RoyalClassLogo-min.png", :style => "width: 100%; margin-top:12px; margin-left:6vw;", :alt => "Royal Class Group logo" %></a>
  </div>
  
  <div class="collapse navbar-collapse" id="myNavbar" style=" border:hidden!important; border-width:0!important;">
    <ul class="nav navbar-nav navbar-right">
      <li class="navlink dropdown">
        <button class="navlink-a dropdown-toggle" type="button" id="dropdown-option-1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">COMPANY</button>
        <ul class="dropdown-menu" aria-labelledby="dropdown-option-1" id="dropdown-menu-1">
          <li><%= link_to 'OUR<br>COMPANY'.html_safe, company_path, 'data-no-turbolink' => true %></li>
          <li role="separator" class="divider"></li>
          <li><%= link_to 'BACKGROUND', '/company/#background', 'data-no-turbolink' => true %></li>
          <li role="separator" class="divider"></li>
          <li><%= link_to 'HISTORICAL<br>TIMELINE'.html_safe, '/company/#timeline', 'data-no-turbolink' => true %></li>
        </ul>
      </li>
      <li class="navlink dropdown">
        <button class="navlink-a dropdown-toggle" type="button" id="dropdown-option-2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">VISION-MISSION</button>
        <ul class="dropdown-menu" aria-labelledby="dropdown-option-2" id="dropdown-menu-2">
          <li><%= link_to 'VISION', '/company/#vision', 'data-no-turbolink' => true %></li>
          <li role="separator" class="divider"></li>
          <li><%= link_to 'MISSION', '/company/#mission', 'data-no-turbolink' => true, onclick:"document.getElementById('mission').style.display='block'" %></li>
          <li role="separator" class="divider"></li>
          <li><%= link_to 'CULTURE OF SERVICE<br>EXCELLENCE'.html_safe, '/company/#customers', 'data-no-turbolink' => true %></li>
        </ul>
      </li>
      <li class="navlink dropdown">
        <button class="navlink-a dropdown-toggle" type="button" id="dropdown-option-3" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">SUBSIDIARIES</button>
        <ul class="dropdown-menu" aria-labelledby="dropdown-option-3" id="dropdown-menu-3">
          <li><%= link_to 'ROYAL CLASS<br>PETROLEUM'.html_safe, rcp_path, 'data-no-turbolink' => true %></li>
          <li role="separator" class="divider"></li>
          <li><%= link_to 'ROYAL CLASS<br>TRANS CORP.'.html_safe, rct_path, 'data-no-turbolink' => true %></li>
          <li role="separator" class="divider"></li>
          <li><%= link_to 'ROYAL CLASS<br>DEVELOPMENT'.html_safe, rcd_path, 'data-no-turbolink' => true %></li>
          <li role="separator" class="divider"></li>
          <li><%= link_to 'JPGLOBAL<br>VENTURES'.html_safe, jpgv_path, 'data-no-turbolink' => true %></li>
          <li role="separator" class="divider"></li>
          <li><%= link_to 'ROYAL CLASS<br>FOUNDATION'.html_safe, rcf_path, 'data-no-turbolink' => true %></li>
        </ul>
      </li>
      <li class="navlink dropdown">
        <button class="navlink-a dropdown-toggle" type="button" id="dropdown-option-4" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">CONTACT</button>
        <ul class="dropdown-menu" aria-labelledby="dropdown-option-4" id="dropdown-menu-4">
          <li><%= link_to 'COMPANY<br>NUMBERS'.html_safe, contact_path, 'data-no-turbolink' => true %></li>
          <li role="separator" class="divider"></li>
          <li><%= link_to 'COMPANY<br>EMAILS'.html_safe, '/contact/#emails', 'data-no-turbolink' => true %></li>
          <li role="separator" class="divider"></li>
          <li><%= link_to 'COMPANY<br>ADDRESS'.html_safe, '/contact/#address', 'data-no-turbolink' => true %></li>
        </ul>
      </li>
    </ul>
  </div>
</div><!-- /.container-fluid -->

app/views/pages/index.html.erb
<!DOCTYPE html>
<% meta title: "Royal Class Group",
    description: "Royal Class Group is driven to be the most preferred provider of quality petroleum products and excellent services.",
    keywords: ["Royal Class", "Royal Class Group","petroleum","Royal Class Petroleum", "Royal Class Trans Corporation", "Royal Class Development", "JPGlobal Ventures", "Royal Class Foundation","Jose Emmanuel 'Joel' P. Guillermo", "oil industry", "fuels", "lubricants","asphalt roads","trucking business","Hauler of Multinational Companies"]
%>
<head>
  <nav class="navbar navbar-default navbar-fixed-top" id="index-navbar">
    <%= render 'pages/navbar' %>
  </nav>
</head>

<body>
  <section id="index-s1" class="index-s">
    <div class="index-text">
      <div class="index-heading">
        OUR COMPANY
      </div>
      <div class="index-description">
        Driven to be the most preferred provider<br>of quality petroleum products<br>and excellent services.
      </div>
      <div class="index-more">
        <%= link_to(company_path, html_options = {class: 'index-more-link'}) do  %>
          >>>
        <% end %>
      </div>
    </div>
  </section>

  <section id="index-s2" class="index-s">
    <div class="index-text">
      <div class="index-heading">
        PHILOSOPHY
      </div>
      <div class="index-description">
        To exceed customer expectations<br>is our business.
      </div>
      <div class="index-more">
        <%= link_to('/company/#culture', html_options = {class: 'index-more-link'}) do  %>
          >>>
        <% end %>
      </div>
    </div>
  </section>

  <section id="index-s3" class="index-s">
    <div class="index-logos" id="subsidiaries">
      <center>
        <%= link_to(rcp_path, html_options = {class: 'view-subsidiary-link'}) do  %>
          <%=image_tag "https://s3.amazonaws.com/royalclass/rcp-fc-min.png", :style => "width: 400px; margin-top: 40px;", :alt => "Royal Class Group RCP logo"%>
        <% end %>
      </center>
      <center>
        <%= link_to(rct_path, html_options = {class: 'view-subsidiary-link'}) do  %>
          <%=image_tag "https://s3.amazonaws.com/royalclass/rct-color-min.png", :style => "width: 600px; margin-top: 90px;", :alt => "Royal Class Group RCT logo"%>
        <% end %>
      </center>
      <center>
        <%= link_to(rcd_path, html_options = {class: 'view-subsidiary-link'}) do  %>
          <%=image_tag "https://s3.amazonaws.com/royalclass/rcd-color-min.png", :style => "width: 400px; margin-top: 90px;", :alt => "Royal Class Group RCD logo"%>
        <% end %>
      </center>
      <center>
        <%= link_to(jpgv_path, html_options = {class: 'view-subsidiary-link'}) do  %>
          <%=image_tag "https://s3.amazonaws.com/royalclass/jpgv-color-min.png", :style => "width: 700px; margin-top: 90px;", :alt => "Royal Class Group JPGV logo"%>
        <% end %>
      </center>
      <center>
        <%= link_to(rcf_path, html_options = {class: 'view-subsidiary-link'}) do  %>
          <%=image_tag "https://s3.amazonaws.com/royalclass/rcf-color-min.png", :style => "width: 400px; margin-top: 90px;", :alt => "Royal Class Group RCF logo"%>
        <% end %>
      </center>
    </div>
  </section>

  <section id="index-s4" class="index-s">
    <div class="index-text">
      <div class="index-heading">
        CONTACT US
      </div>
      <div class="index-description">
        Get in touch with us to know more about our<br>services and products.
      </div>
      <div class="index-more">
        <%= link_to(contact_path, html_options = {class: 'index-more-link'}) do  %>
          LET'S TALK&nbsp;&nbsp;>>>
        <% end %>
      </div>
    </div>
  </section>


</body>

app/views/pages/jpgv.html.erb
<!DOCTYPE html>
<% meta title: "JPGlobal Ventures | Royal Class Group",
    description: "JPGlobal Ventures is engaged in the retailing of fuels and importation of Sinotruk and CIMC vehicles.",
    keywords: ["JPGlobal Ventures","diesel fuels", "gasoline","lubricating oils","shop","service bay","SINOTRUK","CIMC"]
%>
<head>
  <nav class="navbar navbar-default navbar-fixed-top">
    <%= render 'pages/navbar' %>
  </nav>
</head>

<body>
  <section id="jpgv-s1-left">
  </section>
  <section id="jpgv-s1-right">
  </section>
  <%=image_tag "https://s3.amazonaws.com/royalclass/jpgv-color-min.png", :style => "width: 750px; margin-top: 30vh; margin-left: 7vw; position:absolute;", :alt => "JPGlobal Ventures logo" %>
  <div id="jpgv-s1-text">
    Engaged in the retailing of fuels<br>and importation of Sinotruk and CIMC vehicles.
  </div>

  <section id="jpgv-s1">
  </section>

  <section id="jpgv-s2">
    <div class="rc-table-heading">
      <div class="row">
        <div class="col-md-6">
          PRODUCTS & SERVICES
        </div>
        <div class="col-md-6">
          DESCRIPTION
        </div>
      </div>
    </div>

    <div class="rc-table-white-row">
      <div class="row">
        <div class="col-md-6">
         <div class="rc-table-left-col">DIESEL FUELS</div>
        </div>
        <div class="col-md-6">
          <div class="rc-table-right-col">
            <span class="rc-table-right-col-description">Comes in two broad groups, the higher quality and the lower<br>quality product. Automotive Diesel Oil (ADO) which<br>is the higher quality product are used in high speed car<br>and truck engines; while Industrial Diesel Oil (IDO),<br>the lower quality are used in machine engines<br>or in stationary power plants.</span><br><br>
            <span class="rc-table-right-col-heading">The ADO is a biodiesel with the following benefits:</span><br>
            <span class="rc-table-right-col-description">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- Made with 2% Coconut Methyl Ester (CME) in<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;compliance with the 2006 Biofuels Act<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- The 2% CME provides advanced lubrication that<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;protects your engine while facilitating fuel efficiency.<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- More environment-friendly:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- At least Euro IV standard<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- Reduces serious pollutants such as carbon monoxide,<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;hydrocarbons, and other air toxins<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- Biodegradable, non-toxic and essentially free of sulfur<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- More fuel-efficient:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- May help add up to 30% mileage</span>
          </div>
        </div>
      </div>
    </div>

    <div class="rc-table-gray-row">
      <div class="row">
        <div class="col-md-6">
         <div class="rc-table-left-col">GASOLINE FOR CARS<br>AND OTHER VEHICLES</div>
        </div>
        <div class="col-md-6">
          <div class="rc-table-right-col">
            <span class="rc-table-right-col-description">These are also known as petrol and form one of the most<br>important refinery products. The final fuel used in transport<br>which the refinery produces is a carefully blended mixture.<br>An important quality of this fuel is the so called anti-knock<br>quality of gasoline which comes with higher octane rates<br>produced in subsequent refining processes.</span><br><br>
            <span class="rc-table-right-col-heading">The gasoline is a biofuel with the following benefits:</span><br>
            <span class="rc-table-right-col-description">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- Contains 10% ethanol in compliance with<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;the 2006 Biofuels Act<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- More environment-friendly:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- The ethanol content is an oxygenate which helps<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;the gasoline to burn more completely, resulting<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;in less pollution.<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- Reduces emission of carbon monoxide, particulate<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;matter, nitrogen oxides, and other ozone-forming<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;pollutants, thus promoting cleaner emissions.<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- At least Euro IV standard<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- Better for the engine:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- Prevents premature detonation under load<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- Boosts engine power and overall performance<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- More efficient burn resulting in better fuel efficiency<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;and better savings<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- Cleans and protects the engine
            </span>
          </div>
        </div>
      </div>
    </div>

    <div class="rc-table-white-row">
      <div class="row">
        <div class="col-md-6">
         <div class="rc-table-left-col">LUBRICATING OILS</div>
        </div>
        <div class="col-md-6">
          <div class="rc-table-right-col">
            <span class="rc-table-right-col-description">Lubricating Oils comes from a wide range of products from<br>a very fine fluid lubricant to a heavy viscous oil and grease.<br>These are used to lubricate engines used in transportation<br>and in industries.</span>
          </div>
        </div>
      </div>
    </div>

    <div class="rc-table-gray-row">
      <div class="row">
        <div class="col-md-6">
         <div class="rc-table-left-col">SHOP</div>
        </div>
        <div class="col-md-6">
          <div class="rc-table-right-col">
            <span class="rc-table-right-col-description">Convenient Store, Selling of Oils & Lubricant.</span>
          </div>
        </div>
      </div>
    </div>

    <div class="rc-table-white-row">
      <div class="row">
        <div class="col-md-6">
         <div class="rc-table-left-col">SERVICE BAY</div>
        </div>
        <div class="col-md-6">
          <div class="rc-table-right-col">
            <span class="rc-table-right-col-description">Car Wash and Service Bay with mechanics on duty<br>(for car check-up, repairs, and maintenance).</span><br><br>
          </div>
        </div>
      </div>
    </div>

    <div class="rc-table-gray-row">
      <div class="row">
        <div class="col-md-6">
         <div class="rc-table-left-col">SINOTRUCK MAN TECHNOLOGY</div>
        </div>
        <div class="col-md-6">
          <div class="rc-table-right-col">
            <span class="rc-table-right-col-description">Authorized Distributor of Sinotruk products such as Luxury<br>Coach Bus, T7H Tractor Head / Dump Truck / Mining Truck /<br>Mixer Truck/ Cargo Truck & Oil Tanker</span><br><br>
          </div>
        </div>
      </div>
    </div>

    <div class="rc-table-white-row">
      <div class="row">
        <div class="col-md-6">
         <div class="rc-table-left-col">CIMC VEHICLES</div>
        </div>
        <div class="col-md-6">
          <div class="rc-table-right-col">
            <span class="rc-table-right-col-description">Authorized Dealer of CIMC Trailers & Tankers</span><br><br>
          </div>
        </div>
      </div>
    </div>

    <div class="rc-table-view-gallery">
      <%= link_to(jpgv_gallery_path, html_options = {class: 'view-gallery-link'}) do  %>
        VIEW GALLERY
      <% end %>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
      <%= link_to(jpgv_sinotruk_path, html_options = {id: 'view-sinotruk-link'}) do  %>
        SINOTRUK / CIMC DETAILS
      <% end %>
    </div>
  </section>

  <section class="rc-table-footer">
    <div class="rc-table-footer-text">
      <span class="rc-table-footer-heading">FOR INQUIRIES:</span><br>
      <span class="rc-table-footer-description"><%= link_to 'jpglobalventures@yahoo.com', 'https://www.gmail.com', target: '_blank', class: 'contact-email-link-gray' %></span>
    </div>
  </section>

</body>

app/views/pages/jpgv_gallery.html.erb
<!DOCTYPE html>
<% meta title: "JPGlobal Ventures Gallery | Royal Class Group"
%>
<body>
  <section class="rc-gallery">
    <div class="gallery-logo"><center>
      <%= link_to(jpgv_path, html_options = {class: 'back-from-gallery-link'}) do  %> 
        <%= image_tag "https://s3.amazonaws.com/royalclass/arrows_slide_left1-min.png" %>
      <% end %>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
      <%= image_tag "https://s3.amazonaws.com/royalclass/jpgv-color-min.png", :style => "width: 650px;", :alt => "JPGlobal Ventures logo"%>
    </center></div>
    <div class="gallery-images">
      <div class="row">
        <% (1..20).each do |i| %>
          <div class="col-md-4">
            <div class="gallery-image-box" style="background: url(https://s3.amazonaws.com/royalclass/jpgv-<%= i %>.jpg); -ms-background-size: cover; -o-background-size: cover; -moz-background-size: cover; -webkit-background-size: cover; background-size: cover; background-position: center center;"></div>
          </div>
        <% end %>
      </div>
    </div>
  </section>

</body>

app/views/pages/jpgv_sinotruk.html.erb
<!DOCTYPE html>
<% meta title: "JPGlobal Ventures Sinotruk CIMC | Royal Class Group"
%>
<body>
  <section class="rc-gallery">
    <div class="gallery-logo"><center>
      <%= link_to(jpgv_path, html_options = {class: 'back-from-gallery-link'}) do  %> 
        <%= image_tag "https://s3.amazonaws.com/royalclass/arrows_slide_left1-min.png" %>
      <% end %>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
      <%= image_tag "https://s3.amazonaws.com/royalclass/jpgv-color-min.png", :style => "width: 650px;", :alt => "JPGlobal Ventures logo"%>
    </center></div>
    <div class="gallery-images-sinotruk">
      <% (1..6).each do |i| %>
        <div class="gallery-image-box-sinotruk">
          <%= image_tag "https://s3.amazonaws.com/royalclass/cimc-#{i}.jpg", :style => "width: 100%;" %>
        </div>
      <% end %>
    </div>
  </section>

</body>

app/views/pages/rcd.html.erb
<!DOCTYPE html>
<% meta title: "Royal Class Development | Royal Class Group",
    description: "Royal Class Development is engaged in the construction business. We are mainly focused on road construction projects.",
    keywords: ["Royal Class Development","concrete mix","dump trucks","heavy equipment","road construction"]
%>
<head>
  <nav class="navbar navbar-default navbar-fixed-top">
    <%= render 'pages/navbar' %>
  </nav>
</head>

<body>
  <section id="rcd-s1">
    <%=image_tag "https://s3.amazonaws.com/royalclass/rcd-color-min.png", :style => "width: 300px; margin-top: 30vh; margin-left: 7vw;", :alt => "Royal Class Development logo"%>
    <div class="rc-s1-text">
      Engaged in the construction business. It is mainly focused<br>on road construction projects.
    </div>
  </section>

  <section id="rcd-s2">
    <div class="rc-table-heading">
      <div class="row">
        <div class="col-md-6">
          PRODUCTS & SERVICES
        </div>
        <div class="col-md-6">
          DESCRIPTION
        </div>
      </div>
    </div>

    <div class="rc-table-white-row">
      <div class="row">
        <div class="col-md-6">
         <div class="rc-table-left-col">CONCRETE MIX</div>
        </div>
        <div class="col-md-6">
          <div class="rc-table-right-col">
            <span class="rc-table-right-col-description">Aggregates & Cement Mix</span>
          </div>
        </div>
      </div>
    </div>

    <div class="rc-table-gray-row">
      <div class="row">
        <div class="col-md-6">
         <div class="rc-table-left-col">RENTAL OF DUMP TRUCKS<br>& HEAVY EQUIPMENT</div>
        </div>
        <div class="col-md-6">
          <div class="rc-table-right-col">
            <span class="rc-table-right-col-description">Rental of dumptrucks, mixers, backhoes,<br>road rollers, loaders, etc.</span>
          </div>
        </div>
      </div>
    </div>

    <div class="rc-table-white-row">
      <div class="row">
        <div class="col-md-6">
         <div class="rc-table-left-col">ROAD CONSTRUCTION</div>
        </div>
        <div class="col-md-6">
          <div class="rc-table-right-col">
            <span class="rc-table-right-col-description">Road Construction</span>
          </div>
        </div>
      </div>
    </div>
    
    <div class="rc-table-view-gallery">
      <%= link_to(rcd_gallery_path, html_options = {class: 'view-gallery-link'}) do  %>
        VIEW GALLERY
      <% end %>
    </div>
  </section>

  <section class="rc-table-footer">
    <div class="rc-table-footer-text">
      <span class="rc-table-footer-heading">FOR INQUIRIES:</span><br>
      <span class="rc-table-footer-description"><%= link_to 'jpguillermo@gmail.com', 'https://www.gmail.com', target: '_blank', class: 'contact-email-link-gray' %></span>
    </div>
  </section>

</body>